// <auto-generated>
// Opcode tables for the move VISUAL-effect VM ("WEST" = waza-effect script tool), decoded from the leaked
// assembler def src/wazaeffect/west.h (Platinum + HeartGold/SoulSilver). Each we_NNN script (file index = move
// number) is a stream of little-endian 32-bit words: an opcode id (index into the version table below) followed
// by its argument words. Most opcodes are fixed-length; four are VARIABLE — one fixed arg (at CountIndex) holds
// the number of trailing payload words (FUNC_CALL/SE_TASK/EX_DATA/CATS_ACT_ADD). WEST is an orchestration VM
// (loads SPA particles, calls hardcoded C routines via FUNC_CALL, drives BG/camera/sound) so it is NOT visually
// previewable like pokeanm; this table powers a structured script editor / storyboard. Generated — do not edit.
// </auto-generated>
namespace DSPRE.Avalonia.Data
{
    /// <summary>One move-effect (WEST) opcode. <see cref="ArgCount"/> is the fixed argument-word count; if
    /// <see cref="IsVariable"/>, the fixed arg at <see cref="CountIndex"/> additionally gives how many extra
    /// payload words follow.</summary>
    public readonly struct WestOp
    {
        public readonly string Name;
        public readonly int ArgCount;
        public readonly bool IsVariable;
        public readonly int CountIndex;
        public WestOp(string name, int argCount, bool isVariable, int countIndex)
        { Name = name; ArgCount = argCount; IsVariable = isVariable; CountIndex = countIndex; }
    }

    public static class WestOpcodes
    {
        private static readonly WestOp[] Plat =
        {
            new("WEST_WAIT", 1, false, -1),
            new("WEST_WAIT_FLAG", 0, false, -1),
            new("WEST_LOOP_LABEL", 1, false, 0),
            new("WEST_LOOP", 0, false, -1),
            new("WEST_SEQEND", 0, false, -1),
            new("WEST_SE", 1, false, -1),
            new("WEST_POKEBG", 1, false, -1),
            new("WEST_POKEBG_RESET", 1, false, -1),
            new("WEST_BLDALPHA_SET", 2, false, -1),
            new("WEST_BLDALPHA_RESET", 0, false, -1),
            new("WEST_SEQ_CALL", 1, false, -1),
            new("WEST_END_CALL", 0, false, -1),
            new("WEST_WORK_SET", 2, false, -1),
            new("WEST_TURN_CHK", 2, false, -1),
            new("WEST_TURN_JP", 2, false, -1),
            new("WEST_SEQ_JP", 1, false, -1),
            new("WEST_HAIKEI_CHG", 2, false, -1),
            new("WEST_HAIKEI_PARA_CHG", 2, false, -1),
            new("WEST_HAIKEI_RECOVER", 2, false, -1),
            new("WEST_HAIKEI_HALF_WAIT", 0, false, -1),
            new("WEST_HAIKEI_CHG_WAIT", 0, false, -1),
            new("WEST_HAIKEI_SET", 1, false, -1),
            new("WEST_SEPLAY_PAN", 2, false, -1),
            new("WEST_SEPAN", 1, false, -1),
            new("WEST_SEPAN_FLOW", 5, false, -1),
            new("WEST_SE_REPEAT", 4, false, -1),
            new("WEST_SE_WAITPLAY", 3, false, -1),
            new("WEST_BLDCNT_SET", 1, false, -1),
            new("WEST_SE_TASK", 2, true, 1),
            new("WEST_SEWAIT_FLAG", 0, false, -1),
            new("WEST_WORKCHK_JP", 3, false, 1),
            new("WEST_POKEBG_DROP", 2, false, -1),
            new("WEST_POKEBG_DROP_RESET", 1, false, -1),
            new("WEST_CONTEST_CHK_JP", 1, false, -1),
            new("WEST_HAIKEI_CHKCHG", 3, false, -1),
            new("WEST_SEPAN_FLOWFIX", 5, false, -1),
            new("WEST_SEPAN_FLOW_AF", 5, false, -1),
            new("WEST_BGPRI_GAPSET", 1, false, -1),
            new("WEST_BGPRI_GAPSET2", 0, false, -1),
            new("WEST_BGPRI_GAPSET3", 1, false, -1),
            new("WEST_POKE_BANISH_ON", 1, false, -1),
            new("WEST_POKE_BANISH_OFF", 1, false, -1),
            new("WEST_PARTY_ATTACK_BGOFF", 1, false, -1),
            new("WEST_PARTY_ATTACK_BGEND", 1, false, -1),
            new("WEST_SE_STOP", 1, false, -1),
            new("WEST_FUNC_CALL", 2, true, 1),
            new("WEST_ADD_PARTICLE", 3, false, -1),
            new("WEST_ADD_PARTICLE_EMIT_SET", 4, false, -1),
            new("WEST_ADD_PARTICLE_SEP", 8, false, -1),
            new("WEST_ADD_PARTICLE_PTAT", 6, false, -1),
            new("WEST_WAIT_PARTICLE", 0, false, -1),
            new("WEST_LOAD_PARTICLE", 2, false, -1),
            new("WEST_LOAD_PARTICLE_EX", 3, false, -1),
            new("WEST_EXIT_PARTICLE", 1, false, -1),
            new("WEST_OLDACT_FUNC_CALL", 2, true, 1),
            new("WEST_EX_DATA", 1, true, 0),
            new("WEST_POKEOAM_RES_INIT", 0, false, -1),
            new("WEST_POKEOAM_RES_LOAD", 1, false, -1),
            new("WEST_POKEOAM_DROP", 4, false, -1),
            new("WEST_POKEOAM_RES_FREE", 0, false, -1),
            new("WEST_POKEOAM_DROP_RESET", 1, false, -1),
            new("WEST_POKEOAM_AUTO_STOP", 1, false, -1),
            new("WEST_CAMERA_CHG", 2, false, -1),
            new("WEST_CAMERA_REVERCE", 2, false, -1),
            new("WEST_SIDE_JP", 3, false, -1),
            new("WEST_VOICE_PLAY", 3, false, -1),
            new("WEST_VOICE_WAIT_STOP", 1, false, -1),
            new("WEST_WORK_CLEAR", 0, false, -1),
            new("WEST_HENSIN_ON", 1, false, -1),
            new("WEST_HENSIN_ON_RC", 1, false, -1),
            new("WEST_TENKI_JP", 5, false, -1),
            new("WEST_CONTEST_JP", 1, false, -1),
            new("WEST_PTAT_JP", 1, false, -1),
            new("WEST_CATS_RES_INIT", 8, false, -1),
            new("WEST_CATS_CAHR_RES_LOAD", 2, false, -1),
            new("WEST_CATS_PLTT_RES_LOAD", 3, false, -1),
            new("WEST_CATS_CELL_RES_LOAD", 2, false, -1),
            new("WEST_CATS_CELLANM_RES_LOAD", 2, false, -1),
            new("WEST_CATS_ACT_ADD", 9, true, 8),
            new("WEST_CATS_ACT_ADD_EZ", 8, false, -1),
            new("WEST_CATS_RES_FREE", 1, false, -1),
            new("WEST_POKE_OAM_ENABLE", 2, false, -1),
            new("WEST_PT_DROP", 3, false, -1),
            new("WEST_PT_DROP_RESET", 1, false, -1),
            new("WEST_POKEOAM_CHECK", 0, false, -1),
            new("WEST_KEY_WAIT", 0, false, -1),
        };

        private static readonly WestOp[] Hgss =
        {
            new("WEST_WAIT", 1, false, -1),
            new("WEST_WAIT_FLAG", 0, false, -1),
            new("WEST_LOOP_LABEL", 1, false, 0),
            new("WEST_LOOP", 0, false, -1),
            new("WEST_SEQEND", 0, false, -1),
            new("WEST_SE", 1, false, -1),
            new("WEST_POKEBG", 1, false, -1),
            new("WEST_POKEBG_RESET", 1, false, -1),
            new("WEST_BLDALPHA_SET", 2, false, -1),
            new("WEST_BLDALPHA_RESET", 0, false, -1),
            new("WEST_SEQ_CALL", 1, false, -1),
            new("WEST_END_CALL", 0, false, -1),
            new("WEST_WORK_SET", 2, false, -1),
            new("WEST_TURN_CHK", 2, false, -1),
            new("WEST_TURN_JP", 2, false, -1),
            new("WEST_SEQ_JP", 1, false, -1),
            new("WEST_HAIKEI_CHG", 2, false, -1),
            new("WEST_HAIKEI_PARA_CHG", 2, false, -1),
            new("WEST_HAIKEI_RECOVER", 2, false, -1),
            new("WEST_HAIKEI_HALF_WAIT", 0, false, -1),
            new("WEST_HAIKEI_CHG_WAIT", 0, false, -1),
            new("WEST_HAIKEI_SET", 1, false, -1),
            new("WEST_SEPLAY_PAN", 2, false, -1),
            new("WEST_SEPAN", 1, false, -1),
            new("WEST_SEPAN_FLOW", 5, false, -1),
            new("WEST_SE_REPEAT", 4, false, -1),
            new("WEST_SE_WAITPLAY", 3, false, -1),
            new("WEST_BLDCNT_SET", 1, false, -1),
            new("WEST_SE_TASK", 2, true, 1),
            new("WEST_SEWAIT_FLAG", 0, false, -1),
            new("WEST_WORKCHK_JP", 3, false, 1),
            new("WEST_POKEBG_DROP", 2, false, -1),
            new("WEST_POKEBG_DROP_RESET", 1, false, -1),
            new("WEST_CONTEST_CHK_JP", 1, false, -1),
            new("WEST_HAIKEI_CHKCHG", 3, false, -1),
            new("WEST_SEPAN_FLOWFIX", 5, false, -1),
            new("WEST_SEPAN_FLOW_AF", 5, false, -1),
            new("WEST_BGPRI_GAPSET", 1, false, -1),
            new("WEST_BGPRI_GAPSET2", 0, false, -1),
            new("WEST_BGPRI_GAPSET3", 1, false, -1),
            new("WEST_POKE_BANISH_ON", 1, false, -1),
            new("WEST_POKE_BANISH_OFF", 1, false, -1),
            new("WEST_PARTY_ATTACK_BGOFF", 1, false, -1),
            new("WEST_PARTY_ATTACK_BGEND", 1, false, -1),
            new("WEST_SE_STOP", 1, false, -1),
            new("WEST_FUNC_CALL", 2, true, 1),
            new("WEST_ADD_PARTICLE", 3, false, -1),
            new("WEST_ADD_PARTICLE_EMIT_SET", 4, false, -1),
            new("WEST_ADD_PARTICLE_SEP", 8, false, -1),
            new("WEST_ADD_PARTICLE_PTAT", 6, false, -1),
            new("WEST_WAIT_PARTICLE", 0, false, -1),
            new("WEST_LOAD_PARTICLE", 2, false, -1),
            new("WEST_LOAD_PARTICLE_EX", 3, false, -1),
            new("WEST_EXIT_PARTICLE", 1, false, -1),
            new("WEST_OLDACT_FUNC_CALL", 2, true, 1),
            new("WEST_EX_DATA", 1, true, 0),
            new("WEST_POKEOAM_RES_INIT", 0, false, -1),
            new("WEST_POKEOAM_RES_LOAD", 1, false, -1),
            new("WEST_POKEOAM_DROP", 4, false, -1),
            new("WEST_POKEOAM_RES_FREE", 0, false, -1),
            new("WEST_POKEOAM_DROP_RESET", 1, false, -1),
            new("WEST_POKEOAM_AUTO_STOP", 1, false, -1),
            new("WEST_CAMERA_CHG", 2, false, -1),
            new("WEST_CAMERA_REVERCE", 2, false, -1),
            new("WEST_SIDE_JP", 3, false, -1),
            new("WEST_VOICE_PLAY", 3, false, -1),
            new("WEST_VOICE_WAIT_STOP", 1, false, -1),
            new("WEST_WORK_CLEAR", 0, false, -1),
            new("WEST_HENSIN_ON", 1, false, -1),
            new("WEST_HENSIN_ON_RC", 1, false, -1),
            new("WEST_TENKI_JP", 5, false, -1),
            new("WEST_CONTEST_JP", 1, false, -1),
            new("WEST_PTAT_JP", 1, false, -1),
            new("WEST_CATS_RES_INIT", 8, false, -1),
            new("WEST_CATS_CAHR_RES_LOAD", 2, false, -1),
            new("WEST_CATS_PLTT_RES_LOAD", 3, false, -1),
            new("WEST_CATS_CELL_RES_LOAD", 2, false, -1),
            new("WEST_CATS_CELLANM_RES_LOAD", 2, false, -1),
            new("WEST_CATS_ACT_ADD", 9, true, 8),
            new("WEST_CATS_ACT_ADD_EZ", 8, false, -1),
            new("WEST_CATS_RES_FREE", 1, false, -1),
            new("WEST_POKE_OAM_ENABLE", 2, false, -1),
            new("WEST_PT_DROP", 3, false, -1),
            new("WEST_PT_DROP_RESET", 1, false, -1),
            new("WEST_POKEOAM_CHECK", 0, false, -1),
            new("WEST_KEY_WAIT", 0, false, -1),
            new("WEST_FLASH", 1, false, -1),
            new("WEST_HAIKEI_CHG_EX", 3, false, -1),
            new("WEST_BATONTATTI_JP", 1, false, -1),
        };

        public static WestOp[] Table(WazaSeqVersion v) => v == WazaSeqVersion.HGSS ? Hgss : Plat;
        public static int Count(WazaSeqVersion v) => Table(v).Length;
        public static bool TryGet(WazaSeqVersion v, int id, out WestOp op)
        {
            var t = Table(v);
            if (id >= 0 && id < t.Length) { op = t[id]; return true; }
            op = default; return false;
        }
        public static string Name(WazaSeqVersion v, int id) => TryGet(v, id, out var op) ? op.Name : null;
        public static int Id(WazaSeqVersion v, string name)
        {
            var t = Table(v);
            for (int i = 0; i < t.Length; i++) if (t[i].Name == name) return i;
            return -1;
        }
    }
}
